spring:
  thymeleaf:
    cache: false
  h2:
    console:
      enabled: true
      path: "/console"
  datasource:
    url: "jdbc:h2:file:C:/Users/adrian/IdeaProjects/chess/chess-db"
  jpa:
    hibernate:
      ddl-auto: update